### ISSUE TITLE
博客网站打不开了?

### ISSUE THREAD

**Issue by alleluya-young** [chengpeiquan/chengpeiquan.com#161]
作者你好 现在博客https://chengpeiquan.com/打开只有一张图片 文章列表什么的都没有了 请问是停掉了还是什么问题呢?
![image](https://user-images.githubusercontent.com/31433884/135786875-787f9919-e9de-4b14-992a-4314a727945e.png)

**Comment by chengpeiquan** [comment]
Ctrl + F5 强刷一下看看，没有停，我这边打开正常（哈哈哈因为内容比较单一，所以首页一直还没去设计，是我之前看演出拍的一张现场照片）

![1](https://user-images.githubusercontent.com/24845958/135787865-be75d926-d832-438d-bd85-37542d40b568.jpg)
![2](https://user-images.githubusercontent.com/24845958/135787872-aa4b8324-cd2b-4b82-ab77-e63973b2fb7f.jpg)

**Comment by alleluya-young** [comment]
> Ctrl + F5 强刷一下看看，没有停，我这边打开正常（哈哈哈因为内容比较单一，所以首页一直还没去设计，是我之前看演出拍的一张现场照片）
> 
> ![1](https://user-images.githubusercontent.com/24845958/135787865-be75d926-d832-438d-bd85-37542d40b568.jpg) ![2](https://user-images.githubusercontent.com/24845958/135787872-aa4b8324-cd2b-4b82-ab77-e63973b2fb7f.jpg)

好的 感谢 看了下 应该是storage里存的数据是旧的 导致每次请求都是404 clear之后正常了
