### ISSUE TITLE
Oops, there's a major bug in this

### ISSUE THREAD

**Issue by rayadaschn** [chengpeiquan/chengpeiquan.com#363]
(*`ェ´*) 
-------

Sir, the repository hasn't been updated in 4 months. 

When's the annual summary coming out?  （o´ﾟ□ﾟ`o）

![Hurry up](https://synpic.3000test.com/s1/sy/role/20200813/0c81c5c5562359357239f60d668f7e75.png)

**Comment by chengpeiquan** [comment]
![2](https://github.com/chengpeiquan/chengpeiquan.com/assets/24845958/13efea42-a79a-435a-afa0-53a5897b0b06) 

Coming soon... It’s been a busy year, and all my time has been spent typing code…

The longest week of coding ☞

![1](https://github.com/chengpeiquan/chengpeiquan.com/assets/24845958/c8b3372c-a38e-4b10-98b4-be07cfc56b7e)
