### ISSUE TITLE
RSS 订阅地址问题

### ISSUE THREAD

**Issue by AsanZhang** [chengpeiquan/chengpeiquan.com#370]
RSS 订阅地址无法在 NetNewsWire里解析识别，如下图：
<img width="376" alt="image" src="https://github.com/user-attachments/assets/b2cf425b-c6d0-468b-a397-4c8794cc7351">

**Comment by chengpeiquan** [comment]
可能是最近改版引起的，我周末排查一下，多谢反馈！

**Comment by chengpeiquan** [comment]
已经修复了，是 Nginx 的锅，超过限制，流就被截断，导致来到浏览器这里就不完整（改版前直接用 Node 服务没有经过 Nginx 所以没有这个问题，改版后用 Docker + Nginx 所以有一些变化），谢谢你，不然我都没注意到这个问题！

![img_v3_02gv_18b1047e-245b-441c-a40b-05e3cb94db0g](https://github.com/user-attachments/assets/33f78b33-fa6b-4e00-ab54-34bdc90411c7)

目前 Nginx 这边调大了一些限制，Feed 数量我也降低了（毕竟更新也没那么频繁），现在好了～

![img_v3_02gv_ed10868e-5736-4962-94b4-105225e991bg](https://github.com/user-attachments/assets/9c6620ae-fdc7-4b3f-a6d5-de2e32ccb59a)
